export const materialsData = [
  {
    id: "pla",
    name: "PLA",
    family: "FDM",
    shortDescription:
      "Matière simple, économique et adaptée aux prototypes, maquettes et pièces décoratives.",
    resistance: 2,
    temperature: 1,
    uv: 1,
    flexibility: 1,
    finish: 4,
    bestFor: "Prototype / décoration",
    advantages: [
      "Facile à imprimer",
      "Bon rendu visuel",
      "Économique",
      "Large choix de couleurs",
    ],
    limits: [
      "Faible tenue en température",
      "Peu adapté aux fortes contraintes mécaniques",
      "Usage extérieur limité",
    ],
    applications: [
      "Prototype visuel",
      "Maquette",
      "Objet décoratif",
      "Goodies",
    ],
    finishing: [
      "Ponçage",
      "Apprêt",
      "Peinture",
      "Vernis",
    ],
  },
  {
    id: "petg",
    name: "PETG",
    family: "FDM",
    shortDescription:
      "Bon compromis entre résistance mécanique, tenue à l’humidité et facilité d’impression.",
    resistance: 4,
    temperature: 3,
    uv: 3,
    flexibility: 2,
    finish: 3,
    bestFor: "Pièce fonctionnelle",
    advantages: [
      "Bonne résistance mécanique",
      "Bonne tenue à l’humidité",
      "Polyvalent",
      "Adapté aux pièces utiles",
    ],
    limits: [
      "Moins rigide que le PLA",
      "Finition parfois moins fine",
      "Peut marquer légèrement en surface",
    ],
    applications: [
      "Réparation",
      "Support technique",
      "Pièce fonctionnelle",
      "Carter léger",
    ],
    finishing: [
      "Ébavurage",
      "Ponçage",
      "Inserts filetés",
      "Peinture",
    ],
  },
  {
    id: "asa",
    name: "ASA",
    family: "FDM",
    shortDescription:
      "Matière technique adaptée aux pièces extérieures grâce à sa bonne résistance aux UV.",
    resistance: 4,
    temperature: 4,
    uv: 5,
    flexibility: 2,
    finish: 3,
    bestFor: "Extérieur / automobile",
    advantages: [
      "Très bonne tenue aux UV",
      "Bonne tenue en température",
      "Adapté à l’extérieur",
      "Aspect propre",
    ],
    limits: [
      "Impression plus technique",
      "Risque de déformation",
      "Nécessite de bonnes conditions d’impression",
    ],
    applications: [
      "Pièce extérieure",
      "Automobile",
      "Restauration véhicule",
      "Carter exposé",
    ],
    finishing: [
      "Ponçage",
      "Apprêt",
      "Peinture",
      "Vernis",
    ],
  },
  {
    id: "tpu",
    name: "TPU",
    family: "FDM",
    shortDescription:
      "Matière flexible pour pièces souples, protections, joints et éléments amortissants.",
    resistance: 3,
    temperature: 3,
    uv: 3,
    flexibility: 5,
    finish: 2,
    bestFor: "Pièce flexible",
    advantages: [
      "Très souple",
      "Résistant aux chocs",
      "Effet amortissant",
      "Bonne tenue à la déformation",
    ],
    limits: [
      "Moins précis qu’une matière rigide",
      "Impression plus lente",
      "Finition limitée",
    ],
    applications: [
      "Joint",
      "Protection",
      "Silentbloc",
      "Patin souple",
    ],
    finishing: [
      "Ébavurage",
      "Nettoyage",
    ],
  },
  {
    id: "pa12",
    name: "PA12",
    family: "SLS",
    shortDescription:
      "Nylon technique utilisé en frittage poudre pour des pièces complexes, solides et sans support.",
    resistance: 5,
    temperature: 4,
    uv: 4,
    flexibility: 3,
    finish: 4,
    bestFor: "Pièce technique complexe",
    advantages: [
      "Très bonne résistance mécanique",
      "Géométries complexes",
      "Pas de support d’impression",
      "Adapté aux petites séries",
    ],
    limits: [
      "Fabrication via partenaire",
      "Coût supérieur au FDM",
      "Délais variables selon projet",
    ],
    applications: [
      "Pièce mécanique",
      "Assemblage technique",
      "Petite série",
      "Prototype fonctionnel avancé",
    ],
    finishing: [
      "Microbillage",
      "Teinture",
      "Préparation peinture",
    ],
  },
  {
    id: "resine",
    name: "Résine",
    family: "SLA",
    shortDescription:
      "Matière haute précision pour pièces détaillées, prototypes visuels et finitions propres.",
    resistance: 3,
    temperature: 2,
    uv: 2,
    flexibility: 1,
    finish: 5,
    bestFor: "Détail / esthétique",
    advantages: [
      "Très haute précision",
      "Excellent état de surface",
      "Détails fins",
      "Idéal pour présentation",
    ],
    limits: [
      "Plus cassant que le FDM",
      "Volume limité",
      "Post-traitement nécessaire",
    ],
    applications: [
      "Maquette",
      "Prototype visuel",
      "Pièce détaillée",
      "Objet décoratif",
    ],
    finishing: [
      "Nettoyage UV",
      "Ponçage fin",
      "Apprêt",
      "Peinture haute finition",
    ],
  },
];