export const materialsData = [
  {
    id: "pla",
    name: "PLA",
    family: "FDM",
    shortDescription:
      "Matière simple, économique et adaptée aux prototypes, maquettes et pièces décoratives.",
    resistance: 2,
    temperature: 1,
    uv: 1,
    flexibility: 1,
    finish: 4,
    bestFor: "Prototype / décoration",
    advantages: [
      "Facile à imprimer",
      "Bon rendu visuel",
      "Économique",
    ],
    limits: [
      "Faible tenue en température",
      "Usage extérieur limité",
    ],
    applications: [
      "Prototype",
      "Maquette",
      "Objet décoratif",
    ],
    finishing: [
      "Ponçage",
      "Peinture",
    ],
  },

  {
    id: "petg",
    name: "PETG",
    family: "FDM",
    shortDescription:
      "Bon compromis entre résistance mécanique et facilité d’impression.",
    resistance: 4,
    temperature: 3,
    uv: 3,
    flexibility: 2,
    finish: 3,
    bestFor: "Pièce fonctionnelle",
    advantages: [
      "Bonne résistance",
      "Bonne tenue à l’humidité",
      "Polyvalent",
    ],
    limits: [
      "Moins rigide que le PLA",
    ],
    applications: [
      "Réparation",
      "Support technique",
      "Pièce utile",
    ],
    finishing: [
      "Ébavurage",
      "Peinture",
    ],
  },

  {
    id: "asa",
    name: "ASA",
    family: "FDM",
    shortDescription:
      "Matière technique adaptée aux pièces extérieures et automobile.",
    resistance: 4,
    temperature: 4,
    uv: 5,
    flexibility: 2,
    finish: 3,
    bestFor: "Extérieur / automobile",
    advantages: [
      "Très bonne tenue UV",
      "Bonne tenue température",
    ],
    limits: [
      "Impression plus technique",
    ],
    applications: [
      "Automobile",
      "Extérieur",
      "Restauration",
    ],
    finishing: [
      "Ponçage",
      "Peinture",
    ],
  },

  {
    id: "tpu",
    name: "TPU",
    family: "FDM",
    shortDescription:
      "Matière flexible pour protections, joints et amortissement.",
    resistance: 3,
    temperature: 3,
    uv: 3,
    flexibility: 5,
    finish: 2,
    bestFor: "Pièce flexible",
    advantages: [
      "Très souple",
      "Résistant aux chocs",
    ],
    limits: [
      "Impression plus lente",
    ],
    applications: [
      "Joint",
      "Protection",
      "Silentbloc",
    ],
    finishing: [
      "Ébavurage",
    ],
  },
{
  id: "carbone",
  name: "carbone",
  family: "FDM",
  shortDescription:
    "PETG renforcé fibre carbone pour pièces plus rigides et aspect technique.",
  resistance: 4,
  temperature: 3,
  uv: 3,
  flexibility: 1,
  finish: 4,
  bestFor: "Pièce rigide renforcée",
  advantages: ["Plus rigide", "Aspect carbone", "Bonne stabilité"],
  limits: ["Plus abrasif", "Moins souple"],
  applications: ["Support", "Renfort", "Pièce technique"],
  finishing: ["Ébavurage", "Inserts", "Peinture"],
},

{
  id: "abs",
  name: "ABS",
  family: "FDM",
  shortDescription:
    "Matière résistante adaptée aux pièces techniques et post-traitements.",
  resistance: 4,
  temperature: 4,
  uv: 2,
  flexibility: 2,
  finish: 4,
  bestFor: "Pièce technique",
  advantages: ["Bonne résistance", "Lissage possible", "Tenue température"],
  limits: ["Retrait important", "Odeur à l’impression"],
  applications: ["Carter", "Prototype fonctionnel", "Pièce technique"],
  finishing: ["Ponçage", "Lissage acétone", "Peinture"],
},
{
  id: "nylon",
  name: "Nylon",
  family: "SLS / FDM",
  shortDescription:
    "Matière technique résistante, adaptée aux pièces mécaniques et fonctionnelles.",
  resistance: 5,
  temperature: 4,
  uv: 3,
  flexibility: 3,
  finish: 3,
  bestFor: "Pièce mécanique",
  advantages: ["Très résistant", "Bonne tenue à l’usure", "Technique"],
  limits: ["Sensible à l’humidité", "Impression plus exigeante"],
  applications: ["Engrenage", "Support mécanique", "Pièce fonctionnelle"],
  finishing: ["Ébavurage", "Microbillage", "Teinture"],
},
{
  id: "Polycarbonate",
  name: "Polycarbonate",
  family: "FDM",
  shortDescription:
    "Matière technique résistante, adaptée aux pièces mécaniques et fonctionnelles.",
  resistance: 5,
  temperature: 4,
  uv: 3,
  flexibility: 3,
  finish: 3,
  bestFor: "Pièce mécanique",
  advantages: ["Forte", "Durable", "resistante au impact"],
  limits: ["Sensible à l’humidité", "Impression plus exigeante"],
  applications: ["Engrenage", "Support mécanique", "Pièce fonctionnelle"],
  finishing: ["Ébavurage", "Microbillage", "Transluside"],
},
  {
    id: "pa12",
    name: "PA12",
    family: "SLS",
    shortDescription:
      "Nylon technique utilisé en frittage poudre pour pièces complexes.",
    resistance: 5,
    temperature: 4,
    uv: 4,
    flexibility: 3,
    finish: 4,
    bestFor: "Pièce technique",
    advantages: [
      "Très bonne résistance",
      "Géométries complexes",
    ],
    limits: [
      "Fabrication partenaire",
    ],
    applications: [
      "Mécanique",
      "Petite série",
    ],
    finishing: [
      "Microbillage",
      "Teinture",
    ],
  },
  {
  id: "poudre-pa12",
  name: "Poudre PA12",
  family: "SLS",
  shortDescription:
    "Poudre nylon PA12 utilisée en frittage pour pièces complexes et résistantes.",
  resistance: 5,
  temperature: 4,
  uv: 4,
  flexibility: 3,
  finish: 4,
  bestFor: "Pièce technique complexe",
  advantages: ["Sans support", "Solide", "Géométries complexes"],
  limits: ["Fabrication partenaire", "Coût supérieur au FDM"],
  applications: ["Mécanique", "Petite série", "Assemblage"],
  finishing: ["Microbillage", "Teinture", "Peinture"],
},
{
  id: "resine",
  name: "Résine",
  family: "SLA",
  shortDescription:
    "Matière haute précision pour pièces détaillées, prototypes visuels et finitions propres.",
  resistance: 3,
  temperature: 2,
  uv: 2,
  flexibility: 1,
  finish: 5,
  bestFor: "Détail / esthétique",
  advantages: ["Haute précision", "Très bon état de surface", "Détails fins"],
  limits: ["Plus cassant", "Post-traitement nécessaire"],
  applications: ["Maquette", "Prototype visuel", "Objet détaillé"],
  finishing: ["Nettoyage UV", "Ponçage fin", "Peinture"],
},

{
  id: "resine-technique",
  name: "Résine technique",
  family: "SLA",
  shortDescription:
    "Résine renforcée pour prototypes fonctionnels et pièces plus résistantes.",
  resistance: 4,
  temperature: 3,
  uv: 2,
  flexibility: 1,
  finish: 5,
  bestFor: "Prototype fonctionnel précis",
  advantages: ["Précision", "Meilleure résistance", "Très belle finition"],
  limits: ["Coût supérieur", "Volume limité"],
  applications: ["Prototype technique", "Pièce détaillée", "Validation forme"],
  finishing: ["Ponçage fin", "Apprêt", "Peinture"],
},

{
  id: "pmma",
  name: "PMMA",
  family: "Découpe laser",
  shortDescription:
    "Plastique transparent ou coloré utilisé en découpe et gravure laser.",
  resistance: 2,
  temperature: 2,
  uv: 4,
  flexibility: 1,
  finish: 5,
  bestFor: "Signalétique / déco",
  advantages: ["Très belle finition", "Transparent", "Gravable"],
  limits: ["Cassant", "Rayures possibles"],
  applications: ["Signalétique", "Plaque", "Décoration", "Gabarit"],
  finishing: ["Gravure", "Polissage", "Nettoyage"],
},

{
  id: "bois",
  name: "Bois",
  family: "Découpe laser",
  shortDescription:
    "Matériau naturel adapté à la découpe, gravure, maquette et décoration.",
  resistance: 2,
  temperature: 2,
  uv: 2,
  flexibility: 1,
  finish: 4,
  bestFor: "Gravure / décoration",
  advantages: ["Naturel", "Facile à graver", "Rendu chaleureux"],
  limits: ["Sensible à l’humidité", "Épaisseur limitée"],
  applications: ["Maquette", "Décoration", "Signalétique", "Gabarit"],
  finishing: ["Ponçage", "Vernis", "Peinture"],
},

{
  id: "mdf",
  name: "MDF",
  family: "Découpe laser",
  shortDescription:
    "Panneau bois homogène utilisé pour gabarits, maquettes et découpes propres.",
  resistance: 2,
  temperature: 2,
  uv: 1,
  flexibility: 1,
  finish: 3,
  bestFor: "Gabarit / maquette",
  advantages: ["Économique", "Découpe propre", "Stable"],
  limits: ["Sensible à l’humidité", "Aspect moins noble"],
  applications: ["Gabarit", "Maquette", "Support", "Décoration"],
  finishing: ["Ponçage", "Peinture", "Vernis"],
},
];